In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import MissingIndicator,SimpleImputer 

In [3]:
df = pd.read_csv('38_train.csv',usecols=['Age','Fare','Survived'])
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [4]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [47]:
x = df.drop(columns='Survived')
y = df['Survived']

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [49]:
x_train.head()

Age     Fare
51   21.0   7.8000
518  36.0  26.0000
833  23.0   7.8542
805  31.0   7.7750
815   NaN   0.0000

In [50]:
si = SimpleImputer()
X_train_trf = si.fit_transform(x_train)
X_test_trf = si.transform(x_test)

In [51]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6759776536312849

In [68]:
#first way
mi = MissingIndicator()

mi.fit(x_train)

MissingIndicator()

In [53]:
mi.features_

array([0])

In [54]:
X_train_missing = mi.transform(x_train)

In [55]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [56]:
X_test_missing = mi.transform(x_test)

In [57]:
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [58]:
x_train['Age_NA'] = X_train_missing
x_test['Age_NA'] = X_test_missing

In [59]:
x_train

Age      Fare  Age_NA
51   21.0    7.8000   False
518  36.0   26.0000   False
833  23.0    7.8542   False
805  31.0    7.7750   False
815   NaN    0.0000    True
..    ...       ...     ...
712  48.0   52.0000   False
281  28.0    7.8542   False
557   NaN  227.5250    True
888   NaN   23.4500    True
366  60.0   75.2500   False

[712 rows x 3 columns]

In [60]:
x_test

Age      Fare  Age_NA
49   18.0   17.8000   False
34   28.0   82.1708   False
115  21.0    7.9250   False
251  29.0   10.4625   False
91   20.0    7.8542   False
..    ...       ...     ...
636  32.0    7.9250   False
448   5.0   19.2583   False
438  64.0  263.0000   False
540  36.0   71.0000   False
405  34.0   21.0000   False

[179 rows x 3 columns]

In [62]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(x_train)
X_test_trf2 = si.transform(x_test)

In [63]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6871508379888268

In [69]:
#second way
si = SimpleImputer(add_indicator=True)
X_train = si.fit_transform(x_train)
X_test = si.transform(x_test)

In [70]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6871508379888268